// All content (c) Shaun Reed 2021, all rights reserved

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "ActorSpawner.generated.h"

UCLASS(Blueprintable)
class THIRDPERSON_API AActorSpawner : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	AActorSpawner();

  UFUNCTION(BlueprintCallable, Category = "Spawn")
		void SpawnActor();

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	UPROPERTY(EditAnywhere, BlueprintReadWrite)
    class UBoxComponent* SpawnVolume;
public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;

};
